#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Nov 29, 2021 08:12:28 PM CET  platform: Windows NT

import sys
import EC2.py

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import UI_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    UI_support.set_Tk_var()
    top = Toplevel1 (root)
    UI_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    UI_support.set_Tk_var()
    top = Toplevel1 (w)
    UI_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1280x649+-8+-8")
        top.minsize(120, 1)
        top.maxsize(1284, 701)
        top.resizable(0,  0)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Create_Instance = tk.Button(top)
        self.Create_Instance.place(x=1193, y=20, height=24, width=47)
        self.Create_Instance.configure(activebackground="#ececec")
        self.Create_Instance.configure(activeforeground="#000000")
        self.Create_Instance.configure(background="#d9d9d9")
        self.Create_Instance.configure(disabledforeground="#a3a3a3")
        self.Create_Instance.configure(foreground="#000000")
        self.Create_Instance.configure(highlightbackground="#d9d9d9")
        self.Create_Instance.configure(highlightcolor="black")
        self.Create_Instance.configure(pady="0")
        self.Create_Instance.configure(text='''Create''')

        self.Text1 = tk.Text(top)
        self.Text1.place(x=-256, y=274, height=34, width=137)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")

        self.Label1 = tk.Label(top)
        self.Label1.place(x=24, y=218, height=31, width=93)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Instance Name:''')

        self.TEntry1 = ttk.Entry(top)
        self.TEntry1.place(x=120, y=218, height=21, width=756)
        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.Button1 = tk.Button(top)
        self.Button1.place(x=1109, y=216, height=24, width=47)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Stop''')

        self.Button2 = tk.Button(top)
        self.Button2.place(x=1177, y=216, height=24, width=67)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Terminate''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(x=0, y=265, width=1283)

        self.TLabel1 = ttk.Label(top)
        self.TLabel1.place(x=36, y=16, height=27, width=368)
        self.TLabel1.configure(background="#d9d9d9")
        self.TLabel1.configure(foreground="#000000")
        self.TLabel1.configure(font="TkDefaultFont")
        self.TLabel1.configure(relief="flat")
        self.TLabel1.configure(anchor='w')
        self.TLabel1.configure(justify='left')
        self.TLabel1.configure(text='''EC2 Instances''')

        self.Label2 = tk.Label(top)
        self.Label2.place(x=42, y=277, height=31, width=142)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''EC2 Instance Monitoring''')

        self.Label3 = tk.Label(top)
        self.Label3.place(x=47, y=317, height=31, width=77)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Instance ID:''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(x=160, y=317, height=20, width=364)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label4 = tk.Label(top)
        self.Label4.place(x=49, y=355, height=30, width=55)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Region:''')

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(x=161, y=353, height=30, width=114)
        self.TCombobox1.configure(textvariable=UI_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.Label5 = tk.Label(top)
        self.Label5.place(x=54, y=402, height=30, width=77)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Start Duration:''')

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(x=-356, y=533, height=20, width=84)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.TCombobox2 = ttk.Combobox(top)
        self.TCombobox2.place(x=-736, y=606, height=30, width=244)
        self.TCombobox2.configure(textvariable=UI_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(x=-594, y=563, height=20, width=84)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.tooltip_font = "TkDefaultFont"
        self.Entry3_tooltip = \
        ToolTip(self.Entry3, self.tooltip_font, '''DD-MM-YYYY''')

        self.Entry4 = tk.Entry(top)
        self.Entry4.place(x=163, y=404, height=20, width=24)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Entry5 = tk.Entry(top)
        self.Entry5.place(x=-641, y=606, height=20, width=24)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.Entry4_1 = tk.Entry(top)
        self.Entry4_1.place(x=197, y=404, height=20, width=24)
        self.Entry4_1.configure(background="white")
        self.Entry4_1.configure(disabledforeground="#a3a3a3")
        self.Entry4_1.configure(font="TkFixedFont")
        self.Entry4_1.configure(foreground="#000000")
        self.Entry4_1.configure(highlightbackground="#d9d9d9")
        self.Entry4_1.configure(highlightcolor="black")
        self.Entry4_1.configure(insertbackground="black")
        self.Entry4_1.configure(selectbackground="blue")
        self.Entry4_1.configure(selectforeground="white")

        self.Entry4_1_1 = tk.Entry(top)
        self.Entry4_1_1.place(x=230, y=404, height=20, width=24)
        self.Entry4_1_1.configure(background="white")
        self.Entry4_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry4_1_1.configure(font="TkFixedFont")
        self.Entry4_1_1.configure(foreground="#000000")
        self.Entry4_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry4_1_1.configure(highlightcolor="black")
        self.Entry4_1_1.configure(insertbackground="black")
        self.Entry4_1_1.configure(selectbackground="blue")
        self.Entry4_1_1.configure(selectforeground="white")

        self.Entry6 = tk.Entry(top)
        self.Entry6.place(x=-713, y=548, height=120, width=84)
        self.Entry6.configure(background="white")
        self.Entry6.configure(disabledforeground="#a3a3a3")
        self.Entry6.configure(font="TkFixedFont")
        self.Entry6.configure(foreground="#000000")
        self.Entry6.configure(insertbackground="black")

        self.Label6 = tk.Label(top)
        self.Label6.place(x=270, y=400, height=30, width=90)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''End Duration:''')

        self.Entry4_2 = tk.Entry(top)
        self.Entry4_2.place(x=-270, y=460, height=20, width=24)
        self.Entry4_2.configure(background="white")
        self.Entry4_2.configure(disabledforeground="#a3a3a3")
        self.Entry4_2.configure(font="TkFixedFont")
        self.Entry4_2.configure(foreground="#000000")
        self.Entry4_2.configure(highlightbackground="#d9d9d9")
        self.Entry4_2.configure(highlightcolor="black")
        self.Entry4_2.configure(insertbackground="black")
        self.Entry4_2.configure(selectbackground="blue")
        self.Entry4_2.configure(selectforeground="white")

        self.Entry4_2_1 = tk.Entry(top)
        self.Entry4_2_1.place(x=405, y=403, height=20, width=24)
        self.Entry4_2_1.configure(background="white")
        self.Entry4_2_1.configure(disabledforeground="#a3a3a3")
        self.Entry4_2_1.configure(font="TkFixedFont")
        self.Entry4_2_1.configure(foreground="#000000")
        self.Entry4_2_1.configure(highlightbackground="#d9d9d9")
        self.Entry4_2_1.configure(highlightcolor="black")
        self.Entry4_2_1.configure(insertbackground="black")
        self.Entry4_2_1.configure(selectbackground="blue")
        self.Entry4_2_1.configure(selectforeground="white")

        self.Entry4_2_1_1 = tk.Entry(top)
        self.Entry4_2_1_1.place(x=438, y=403, height=20, width=24)
        self.Entry4_2_1_1.configure(background="white")
        self.Entry4_2_1_1.configure(disabledforeground="#a3a3a3")
        self.Entry4_2_1_1.configure(font="TkFixedFont")
        self.Entry4_2_1_1.configure(foreground="#000000")
        self.Entry4_2_1_1.configure(highlightbackground="#d9d9d9")
        self.Entry4_2_1_1.configure(highlightcolor="black")
        self.Entry4_2_1_1.configure(insertbackground="black")
        self.Entry4_2_1_1.configure(selectbackground="blue")
        self.Entry4_2_1_1.configure(selectforeground="white")

        self.Entry4_2_1_2 = tk.Entry(top)
        self.Entry4_2_1_2.place(x=373, y=403, height=20, width=24)
        self.Entry4_2_1_2.configure(background="white")
        self.Entry4_2_1_2.configure(disabledforeground="#a3a3a3")
        self.Entry4_2_1_2.configure(font="TkFixedFont")
        self.Entry4_2_1_2.configure(foreground="#000000")
        self.Entry4_2_1_2.configure(highlightbackground="#d9d9d9")
        self.Entry4_2_1_2.configure(highlightcolor="black")
        self.Entry4_2_1_2.configure(insertbackground="black")
        self.Entry4_2_1_2.configure(selectbackground="blue")
        self.Entry4_2_1_2.configure(selectforeground="white")

        self.Button3 = tk.Button(top)
        self.Button3.place(x=479, y=400, height=24, width=45)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Start''')

        self.Scrolledlistbox1 = ScrolledListBox(top)
        self.Scrolledlistbox1.place(x=30, y=50, height=155, width=1221)
        self.Scrolledlistbox1.configure(background="white")
        self.Scrolledlistbox1.configure(cursor="xterm")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(font="TkFixedFont")
        self.Scrolledlistbox1.configure(foreground="black")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="blue")
        self.Scrolledlistbox1.configure(selectforeground="white")
        self.Scrolledlistbox1.bind()

        self.TSeparator2 = ttk.Separator(top)
        self.TSeparator2.place(x=571, y=269, height=200)
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator3 = ttk.Separator(top)
        self.TSeparator3.place(x=5, y=474, width=1270)

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Message1 = tk.Message(top)
        self.Message1.place(x=580, y=280, height=173, width=680)
        self.Message1.configure(background="#d9d9d9")
        self.Message1.configure(foreground="#000000")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Message''')
        self.Message1.configure(width=680)

# Declare functions for main GUI
    def showFrame(self, event):
        """
        Shows the frame and shows the message sent in the
        text control
        """
        new_frame = CreateInstance(parent=self.panel)
        new_frame.Show()

    def selectRegion(self, event):
        self.region = self.reg_sel_dropdown.GetValue()
        self.get_instances = get_running_instances(self.region)
        #self.grid.AppendText(self.get_instances)
        print(self.get_instances)
        for row in range(len(self.get_instances)):
            for col in range(3):
                self.grid.SetCellValue(row,col,self.get_instances[row][col])
      #  event.Skip()
    
    def runInstance(self, event):
        self.region = self.reg_sel_dropdown.GetValue()
        self.instanceID = self.id_input.GetValue()
        self.output = start_instance(self.instanceID, self.region )
     #   event.Skip()

    def stopInstance(self, event):
        self.region = self.reg_sel_dropdown.GetValue()
        self.instanceID = self.id_input.GetValue()
        self.output = stop_instance(self.instanceID, self.region)
     #   event.Skip()
    
    def terminateInstance(self,event):
        self.region = self.reg_sel_dropdown.GetValue()
        self.instanceID = self.id_input.GetValue()
        self.output = terminate_instance(self.instanceID, self.region)

    def monitorInstance(self, event):
        self.region = self.reg_sel_dropdown.GetValue()
        self.instanceID = self.monitor_in.GetValue()
        self.From = self.datepicker_from.GetValue()
        self.To = self.datepicker_to.GetValue()
        self.startTime = str(self.From.Format('%d/%m/%y'))
        self.endTime = str(self.To.Format('%d/%m/%y'))
        self.response = monitor_cpu(self.instanceID, self.startTime , self.endTime, self.region)
        self.output_2.SetValue(str("CPU Utilization: " + str(self.response)))
        print(self.response)
# end of class MyFrame



# ======================================================
# Support code for Balloon Help (also called tooltips).
# Found the original code at:
# http://code.activestate.com/recipes/576688-tooltip-for-tkinter/
# Modified by Rozen to remove Tkinter import statements and to receive
# the font as an argument.
# ======================================================

from time import time, localtime, strftime

class ToolTip(tk.Toplevel):
    """
    Provides a ToolTip widget for Tkinter.
    To apply a ToolTip to any Tkinter widget, simply pass the widget to the
    ToolTip constructor
    """
    def __init__(self, wdgt, tooltip_font, msg=None, msgFunc=None,
                 delay=0.5, follow=True):
        """
        Initialize the ToolTip

        Arguments:
          wdgt: The widget this ToolTip is assigned to
          tooltip_font: Font to be used
          msg:  A static string message assigned to the ToolTip
          msgFunc: A function that retrieves a string to use as the ToolTip text
          delay:   The delay in seconds before the ToolTip appears(may be float)
          follow:  If True, the ToolTip follows motion, otherwise hides
        """
        self.wdgt = wdgt
        # The parent of the ToolTip is the parent of the ToolTips widget
        self.parent = self.wdgt.master
        # Initalise the Toplevel
        tk.Toplevel.__init__(self, self.parent, bg='black', padx=1, pady=1)
        # Hide initially
        self.withdraw()
        # The ToolTip Toplevel should have no frame or title bar
        self.overrideredirect(True)

        # The msgVar will contain the text displayed by the ToolTip
        self.msgVar = tk.StringVar()
        if msg is None:
            self.msgVar.set('No message provided')
        else:
            self.msgVar.set(msg)
        self.msgFunc = msgFunc
        self.delay = delay
        self.follow = follow
        self.visible = 0
        self.lastMotion = 0
        # The text of the ToolTip is displayed in a Message widget
        tk.Message(self, textvariable=self.msgVar, bg='#FFFFDD',
                font=tooltip_font,
                aspect=1000).grid()

        # Add bindings to the widget.  This will NOT override
        # bindings that the widget already has
        self.wdgt.bind('<Enter>', self.spawn, '+')
        self.wdgt.bind('<Leave>', self.hide, '+')
        self.wdgt.bind('<Motion>', self.move, '+')

    def spawn(self, event=None):
        """
        Spawn the ToolTip.  This simply makes the ToolTip eligible for display.
        Usually this is caused by entering the widget

        Arguments:
          event: The event that called this funciton
        """
        self.visible = 1
        # The after function takes a time argument in milliseconds
        self.after(int(self.delay * 1000), self.show)

    def show(self):
        """
        Displays the ToolTip if the time delay has been long enough
        """
        if self.visible == 1 and time() - self.lastMotion > self.delay:
            self.visible = 2
        if self.visible == 2:
            self.deiconify()

    def move(self, event):
        """
        Processes motion within the widget.
        Arguments:
          event: The event that called this function
        """
        self.lastMotion = time()
        # If the follow flag is not set, motion within the
        # widget will make the ToolTip disappear
        #
        if self.follow is False:
            self.withdraw()
            self.visible = 1

        # Offset the ToolTip 10x10 pixes southwest of the pointer
        self.geometry('+%i+%i' % (event.x_root+20, event.y_root-10))
        try:
            # Try to call the message function.  Will not change
            # the message if the message function is None or
            # the message function fails
            self.msgVar.set(self.msgFunc())
        except:
            pass
        self.after(int(self.delay * 1000), self.show)

    def hide(self, event=None):
        """
        Hides the ToolTip.  Usually this is caused by leaving the widget
        Arguments:
          event: The event that called this function
        """
        self.visible = 0
        self.withdraw()

    def update(self, msg):
        """
        Updates the Tooltip with a new message. Added by Rozen
        """
        self.msgVar.set(msg)

# ===========================================================
#                   End of Class ToolTip
# ===========================================================

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





