#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.3 on Tue Nov 30 14:20:24 2021
#

import wx
import ec2_functions as ec2f

# begin wxGlade: dependencies
import wx.adv
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((600, 500))
        self.SetTitle("AWS Monitoring")
        self.SetBackgroundColour(wx.Colour(118, 148, 0))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 0, wx.EXPAND, 0)

        alabel_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Region :")
        sizer_2.Add(alabel_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        self.refreshRegion_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_2.Add(self.refreshRegion_input, 1, wx.LEFT | wx.RIGHT, 10)

        self.refresh_button = wx.Button(self.panel_1, wx.ID_ANY, "Refresh")
        sizer_2.Add(self.refresh_button, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 10)

        self.createInstance_button = wx.Button(self.panel_1, wx.ID_ANY, "Create Instance")
        self.createInstance_button.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_2.Add(self.createInstance_button, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 10)

        self.grid_1 = wx.grid.Grid(self.panel_1, wx.ID_ANY, size=(1, 1))
        #sizer_1.Add(self.grid_1, 1, wx.EXPAND, 0)
        self.grid_1.CreateGrid(20, 3)
        self.grid_1.SetMinSize((620, 200))
        self.grid_1.SetColLabelValue(0,"Instance ID")
        self.grid_1.SetColSize(0,200)
        self.grid_1.SetColLabelValue(1,"Instance Type")
        self.grid_1.SetColSize(1,150)
        self.grid_1.SetColLabelValue(2,"Security Group")
        self.grid_1.SetColSize(2,270)
        sizer_1.Add(self.grid_1, 1, wx.ALL | wx.EXPAND, 1)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Enter Instance Name :")
        sizer_3.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        self.instance_name_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_3.Add(self.instance_name_input, 2, wx.LEFT | wx.RIGHT, 10)

        self.stop_button = wx.Button(self.panel_1, wx.ID_ANY, "Stop")
        sizer_3.Add(self.stop_button, 1, wx.LEFT | wx.RIGHT, 10)

        self.terminate_button = wx.Button(self.panel_1, wx.ID_ANY, "Terminate")
        sizer_3.Add(self.terminate_button, 1, wx.LEFT | wx.RIGHT, 10)

        static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line_1, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 10)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Monitoring")
        sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Enter Instance ID :")
        sizer_4.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        self.instanceId_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_4.Add(self.instanceId_input, 4, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 110)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Enter Region :")
        sizer_5.Add(label_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        self.region_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_5.Add(self.region_input, 4, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 110)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_6, 1, wx.EXPAND | wx.RIGHT, 110)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Monitoring Duration :")
        sizer_6.Add(label_5, 8, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        self.datepicker_ctrl_1 = wx.adv.DatePickerCtrl(self.panel_1, wx.ID_ANY)
        sizer_6.Add(self.datepicker_ctrl_1, 15, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 5)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "-")
        sizer_6.Add(label_6, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.datepicker_ctrl_2 = wx.adv.DatePickerCtrl(self.panel_1, wx.ID_ANY)
        sizer_6.Add(self.datepicker_ctrl_2, 15, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        self.monitor_button = wx.Button(self.panel_1, wx.ID_ANY, "Start Monitoring")
        sizer_1.Add(self.monitor_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM | wx.TOP, 7)

        self.monitoring_output = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        #self.monitoring_output.Hide()
        sizer_1.Add(self.monitoring_output, 0, wx.ALL | wx.EXPAND, 5)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade
        #bind functions
        self.Bind(wx.EVT_BUTTON, self.showFrame, self.createInstance_button)

        self.Bind(wx.EVT_BUTTON, self.selectRegion, self.refresh_button)
        
        self.Bind(wx.EVT_BUTTON, self.stopInstance, self.stop_button)
        
        self.Bind(wx.EVT_BUTTON, self.monitorInstance, self.monitor_button)

   # Declare functions for main GUI
    def showFrame(self, event):
        """
        Shows the frame and shows the message sent in the
        text control
        """
        new_frame = MyFrame1(parent=self.panel_1)
        new_frame.Show()

    def selectRegion(self, event):
        self.region = self.refreshRegion_input.GetValue()
        self.get_instances = ec2f.get_running_instances(self.region)
        #self.grid.AppendText(self.get_instances)
        print(self.get_instances)
        for row in range(len(self.get_instances)):
            for col in range(3):
                self.grid_1.SetCellValue(row,col,self.get_instances[row][col])
                
    def stopInstance(self, event):
        self.region = self.refreshRegion_input.GetValue()
        self.instanceID = self.instance_name_input.GetValue()
        self.output = ec2f.stop_instance(self.instanceID, self.region)
     #   event.Skip()
     
    def terminateInstance(self,event):
        self.region = self.refreshRegion_input.GetValue()
        self.instanceID = self.instance_name_input.GetValue()
        self.output = ec2f.terminate_instance(self.instanceID, self.region)
    
    def monitorInstance(self, event):
        self.region = self.region_input.GetValue()
        self.instanceID = self.instanceId_input.GetValue()
        self.From = self.datepicker_ctrl_1.GetValue()
        self.To = self.datepicker_ctrl_2.GetValue()
        self.startTime = str(self.From.Format('%d/%m/%y'))
        self.endTime = str(self.To.Format('%d/%m/%y'))
        self.response = ec2f.monitor_cpu(self.instanceID, self.startTime , self.endTime, self.region)
        self.monitoring_output.SetValue(str("CPU Utilization: " + str(self.response)))
        #self.monitoring_output.Hide()
        print(self.response)
# end of class MyFrame

class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((470, 200))
        self.SetTitle("Create Instance")
        self.SetBackgroundColour(wx.Colour(255, 50, 255))
        self.SetForegroundColour(wx.Colour(24, 143, 93))
        self.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, ""))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.ALL | wx.EXPAND, 1)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Instance Type:")
        sizer_4.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 10)

        self.CI_Type_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.CI_Type_input.SetMinSize((250, 23))
        self.CI_Type_input.SetBackgroundColour(wx.Colour(46, 42, 255))
        sizer_4.Add(self.CI_Type_input, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Region :")
        sizer_5.Add(label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 26)

        self.CI_Region_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.CI_Region_input.SetMinSize((250, 23))
        sizer_5.Add(self.CI_Region_input, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Security Group :")
        sizer_6.Add(label_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 6)

        self.CI_SG_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.CI_SG_input.SetMinSize((250, 23))
        sizer_6.Add(self.CI_SG_input, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Key Pair : ")
        sizer_7.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 23)

        self.CI_KP_input = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.CI_KP_input.SetMinSize((250, 23))
        sizer_7.Add(self.CI_KP_input, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)

        self.CI_create_button = wx.Button(self.panel_1, wx.ID_ANY, "Create")
        sizer_7.Add(self.CI_create_button, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 18)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade
        # Bind functions to buttons 
        self.Bind(wx.EVT_BUTTON, self.createInstance, self.CI_create_button)

        # Declare Function
    def createInstance(self, event):
        self.ima = "ami-0bd9c26722573e69b"
        self.type_i = self.CI_Type_input.GetValue()
        self.key = self.CI_KP_input.GetValue()
        self.sg = self.CI_SG_input.GetValue()
        self.region = self.CI_Region_input.GetValue()
        self.response = ec2f.create_instance(self.ima,self.type_i,self.key,self.sg,self.region)
        print(self.response)

# end of class MyFrame1

class MyApp(wx.App):
    def OnInit(self):
        self.frame_main = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_main)
        self.frame_main.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
